import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

const BLUE = "#3B5BDB";
const SURFACE = "#F0F2F8";

export const styles = StyleSheet.create({
  scroll: { paddingBottom: 32 },

  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  checkBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: BLUE,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: BLUE,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  toggleWrapper: { paddingHorizontal: 20, marginTop: 20, marginBottom: 20 },
  toggleContainer: {
    flexDirection: "row",
    backgroundColor: "#E8EDF5",
    borderRadius: 50,
    padding: 4,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleBtnActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  toggleText: { fontSize: 15, fontWeight: "700", color: "#94A3B8" },
  toggleTextActive: { color: BLUE },

  amountCard: {
    marginHorizontal: 20,
    marginBottom: 24,
    backgroundColor: "#fff",
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOpacity: 0,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  amountInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 20,
  },
  currencySection: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  currencySymbol: {
    fontSize: 24,
    fontWeight: "800",
    color: BLUE,
  },
  amountDivider: {
    width: 2,
    height: 40,
    backgroundColor: "#E8EDF5",
    marginRight: 16,
    borderRadius: 1,
  },
  amountSection: {
    flex: 1,
    justifyContent: "center",
  },
  amountValue: {
    fontSize: 44,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -1.5,
    lineHeight: 52,
  },

  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94A3B8",
    letterSpacing: 1.5,
  },
  seeAllText: { fontSize: 13, fontWeight: "600", color: BLUE },

  catSection: { marginBottom: 24 },
  categoriesRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 10,
  },
  categoryItem: {
    alignItems: "center",
    gap: 8,
    width: (width - 80) / 5,
  },
  categoryItemActive: {},
  categoryBox: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryBoxActive: {
    borderWidth: 2,
    borderColor: BLUE,
  },
  categoryLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#64748B",
    textAlign: "center",
    maxWidth: 60,
  },
  categoryLabelActive: { color: BLUE, fontWeight: "700" },
  categoryCheck: {
    position: "absolute",
    top: -4,
    right: -4,
  },
  createCategoryCard: {
    alignItems: "center",
    gap: 8,
    width: (width - 80) / 5,
  },
  createCategoryIcon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: BLUE,
    borderStyle: "dashed",
  },
  createCategoryLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: BLUE,
  },

  quickAddSection: { marginBottom: 24 },
  quickAddRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 12,
  },
  quickAddItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  quickAddIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  quickAddLabel: { fontSize: 14, fontWeight: "700", color: "#0F172A" },
  quickAddAmount: { fontSize: 12, color: "#94A3B8", marginTop: 2 },

  modalContainer: {
    flex: 1,
    backgroundColor: SURFACE,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    backgroundColor: "#fff",
  },
  modalClose: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  modalBody: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  modalPreview: {
    alignItems: "center",
    paddingVertical: 24,
  },
  modalPreviewIcon: {
    width: 72,
    height: 72,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  modalPreviewLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  modalField: {
    marginBottom: 24,
  },
  modalFieldLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94A3B8",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  modalInput: {
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: "600",
    color: "#0F172A",
    borderWidth: 2,
    borderColor: "transparent",
  },
  modalInputError: {
    borderColor: "#EF4444",
  },
  modalError: {
    fontSize: 12,
    color: "#EF4444",
    fontWeight: "600",
    marginTop: 6,
  },
  modalIconGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  modalIconOption: {
    width: 46,
    height: 46,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "transparent",
  },
  modalIconOptionSelected: {
    borderColor: BLUE,
    backgroundColor: "#EEF2FF",
  },
  modalColorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  modalColorOption: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "transparent",
  },
  modalColorOptionSelected: {
    borderColor: "#fff",
  },
  modalFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    backgroundColor: "#fff",
  },
  modalCreateBtn: {
    backgroundColor: BLUE,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
  },
  modalCreateBtnDisabled: {
    backgroundColor: "#94A3B8",
  },
  modalCreateBtnText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
});
