import { StyleSheet } from "react-native";

const BLUE = "#3B5BDB";

export const styles = StyleSheet.create({
  scroll: { flexGrow: 1, paddingBottom: 32 },
  container: { paddingHorizontal: 20, paddingTop: 16 },

  // ── Premium Blue Card ──
  balanceCard: {
    borderRadius: 28,
    padding: 24,
    marginBottom: 28,
    backgroundColor: BLUE,
    shadowColor: BLUE,
    shadowOpacity: 0.45,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
    overflow: "hidden",
  },
  balanceCardAccent: {
    position: "absolute",
    top: -60,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  balanceCardAccent2: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  balanceLabel: {
    fontSize: 14,
    color: "rgba(255,255,255,0.75)",
    fontWeight: "500",
  },
  cardTypeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  cardTypeBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.8,
  },
  balanceAmount: {
    fontSize: 40,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -1,
    marginBottom: 20,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginBottom: 20,
  },
  cardBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  visaGroup: { flexDirection: "row", alignItems: "center" },
  visaCircle1: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#1A3CB8",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
  },
  visaCircle2: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2D4ED8",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -14,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
  },
  visaText: { fontSize: 9, fontWeight: "800", color: "#fff" },
  addMoneyBtn: {
    backgroundColor: "#fff",
    borderRadius: 50,
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addMoneyBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: BLUE,
  },

  // ── Section Header ──
  sectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -0.4,
  },

  // ── Activity ──
  activityCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingHorizontal: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  activityItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  activityIconWrapper: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  activityInfo: { flex: 1 },
  activityTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 3,
  },
  activityTime: { fontSize: 12, color: "#94A3B8" },
  activityAmount: { fontSize: 15, fontWeight: "700" },
  activityNeg: { color: "#0F172A" },
  activityPos: { color: "#16A34A" },

  // ── Empty Activity ──
  emptyActivity: {
    alignItems: "center",
    paddingVertical: 40,
    gap: 8,
  },
  emptyActivityText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#94A3B8",
  },
  emptyActivitySubtext: {
    fontSize: 13,
    color: "#CBD5E1",
  },

  // ── Loading ──
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },

  // ── Add Money Modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 40,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#CBD5E1",
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 24,
  },
  modalInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 60,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    marginBottom: 20,
  },
  modalInputFocused: {
    borderColor: BLUE,
  },
  modalCurrencySign: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0F172A",
    marginRight: 8,
  },
  modalInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: "700",
    color: "#0F172A",
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
  },
  modalCancelBtn: {
    flex: 1,
    height: 52,
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCancelText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#64748B",
  },
  modalSaveBtn: {
    flex: 2,
    height: 52,
    borderRadius: 14,
    backgroundColor: BLUE,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  modalSaveDisabled: {
    opacity: 0.6,
  },
  modalSaveText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },

  // ── Success Overlay ──
  successOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(22,163,74,0.95)",
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  successCheck: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  successTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 4,
  },
  successSubtitle: {
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
  },
});
